### PR TITLE
Raise exception on failure rather than SIGPIPE signal

### PR DESCRIPTION
**Pull request by matthill**
PR for issue #30

### CODE REVIEW

**Comment by deepfryed** [comment]
@matthill could you rename `BeanstalkConnectException` to `ConnectException` ?

**Comment by deepfryed** [comment]
Looks good otherwise.

**Comment by deepfryed** [comment]
It's late in the night here, I'll have a look tomorrow morning and merge. :zzz:

**Comment by matthill** [comment]
OK.  This is done.  FYI, I didn't throw exceptions for all the C++ wrappers (e.g., put, peek, list_tubes, etc).  Not because we shouldn't, just laziness I suppose.

**Comment by deepfryed** [comment]
thanks @matthill :+1:

**Pull request merged**
